[jenkins_master]
54.152.13.63 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/labs_kp.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[jenkins_agent]
18.204.210.79 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/labs_kp.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[sonarqube]
13.220.251.18 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/labs_kp.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
