---
- name: Configure SonarQube
  hosts: SonarQube
  become: yes
  vars:
    aws_region: "us-east-1"
    sonar_db_username_ssm: "/sonarqube/db-username"
    sonar_db_password_ssm: "/sonarqube/db-password"
    sonar_db_name: "sonarqube"
    sonar_admin_password: "{{ lookup('env', 'SONAR_ADMIN_PASSWORD') | default('admin', true) }}"
    jenkins_master_ip: "{{ hostvars[groups['Jenkins_Master'][0]].ansible_host }}"

  roles:
    - common
    - sonarqube
